### PR TITLE
`Edit Settings` command opens JSON file

### LINKED ISSUE #227: Easy Access to setting.json
Type: <b>Bug</b>

Hi,
It would be great to be able to access settings.json directly from the "servers" view without having to search for setting-intersystems and so on.

Thanks,
Mark

Extension version: 3.6.1
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.62GB (10.70GB free)|
|Process Argv|--crash-reporter-id 6e1da3bb-9b02-4f5b-9446-28dcb121dc70|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes #227

### CODE REVIEW

**Review by gjsjohnmurray — COMMENTED** [review]
I have also been looking at this, and in future we should probably do a better job of coordinating who's working on what.

Opening settings as JSON at a particular key can already be done more simply:

```ts
	vscode.commands.executeCommand("workbench.action.openSettingsJson", { revealSetting: { key: "intersystems.servers" } });
```

But because of the way our package.json defines this object the following **doesn't** go to the specific entry:

```ts
	vscode.commands.executeCommand("workbench.action.openSettingsJson", { revealSetting: { key: `intersystems.servers.${server.name}` } });
```

So I suggest you refine your `revealServers` technique to find the sub-object that matches server.name (perhaps rename the function revealServer).

It might be safer not to select any characters though, as doing so creates a risk of the user inadvertently deleting or overtyping.

**Comment by gjsjohnmurray** [comment]
revealSetting should be able to get you close, but I suggest you augment it with a forward scan to find the definition of the actual server the user invoked the command from.

File: src/extension.ts [hunk 1]
```diff
@@ -137,8 +137,39 @@ export function activate(context: vscode.ExtensionContext) {
...
+				const regex = new RegExp(`"${server?.name}"\\s*:`);
+				if (editor && (editor.document.uri.path.endsWith("/settings.json") || editor.document.uri.path.endsWith(".code-workspace"))) {
+					// The cursor is currently at "|intersystems.servers", so start our scan from there
+					for (let i = editor.selection.start.line; i < editor.document.lineCount; i++) {
+						const line = editor.document.lineAt(i).text;
+						const match = regex.exec(line);
+						const commentStart = line.indexOf("//");
+						if (match && (commentStart == -1 || match.index < commentStart)) {
+							const cursorPos = new vscode.Position(i, match.index + 1);
+							editor.revealRange(new vscode.Range(cursorPos, cursorPos));
```
Comment (gjsjohnmurray) [inline src/extension.ts:156]: I suggest you use `revealRange`'s optional second argument to position the setting in the center of the viewport.

**Review by gjsjohnmurray — APPROVED** [review]
:+1:
